// Bundles views/*.html into lib/pages.js so the server never reads HTML from disk
// (serverless hosts like Vercel don't always ship loose files with the function).
// Run after editing anything in views/:  npm run build:pages
import fs from 'node:fs';

const dir = new URL('../views/', import.meta.url);
const pages = Object.fromEntries(fs.readdirSync(dir).filter((f) => f.endsWith('.html')).sort()
  .map((f) => [f.replace(/\.html$/, ''), fs.readFileSync(new URL(f, dir), 'utf8')]));
const out = `// Generated by scripts/build-pages.mjs from views/*.html. Do not edit by hand.
const PAGES = ${JSON.stringify(pages, null, 1)};

const APP_NAME = process.env.APP_NAME || 'Slotly';

export function renderPage(name) {
  const html = PAGES[name];
  if (!html) throw new Error(\`Unknown page: \${name}\`);
  return APP_NAME === 'Slotly' ? html : html.replaceAll('Slotly', APP_NAME);
}
`;
fs.writeFileSync(new URL('../lib/pages.js', import.meta.url), out);
console.log(`Wrote lib/pages.js (${Object.keys(pages).length} pages)`);
